name: CI Integration Tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-10.15
    name: Integration test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run tests with pytest
        run: pytest
